---
title: "Bach Analysis"
author: "Taqi"
# date: "4/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load libraries
library(tidyverse)
# Source files
source("../R-museR/header.R")
.src(1)
source("../R/header.R")
.src(1)
```

```{r}
# Bach score file path
bach_spline <- "../data-krn/bach_C_notes.krn"
bach <- kern2df(bach_spline)
```

```{r}
bach_notes <- .obtainNotes(.getScoreNotes(bach))
freqs <- SD_freq(bach_notes, "C")
```


```{r}

```

```{r}
modality <- function(freqs, quality = NA){
  # Use the quality to study modality
  if(quality == "major"){ return (.modalityMajor(freqs)) }
  else if(quality == "minor"){ return (.modalityMinor(freqs)) }
}
.modalityMinor <- function(freqs){
  # Get the total number of notes
  total <- sum(freqs)
  # Create a data frame of features
  modality <- data.frame(blues = 0)
  # Blues
  modality$blues <- .countFreqs(c("3","#4","b5"), freqs)
  # Interchange
  modality$interchange <- .countFreqs(c("b2","6"), freqs)
  # Borrowed subdominant 
  modality$borrowed_sub <- .countFreqs(c("6"), freqs)
  # Return the features
  modality/total
}
.modalityMajor <- function(freqs){
  # Get the total number of notes
  total <- sum(freqs)
  # Create a data frame of features
  modality <- data.frame(blues = 0)
  # Blues
  modality$blues <- .countFreqs(c("b3","#4","b5","b6"), freqs)
  # Interchange
  modality$interchange <- .countFreqs(c("#4","b6","b7"),freqs)
  # Borrowed subdominant 
  modality$borrowed_sub <- .countFreqs(c("b6"), freqs)
  # Return the features
  modality/total
}
```

```{r}
.modalityMajor(freqs)
```


```{r}

```


```{r}
TDS_class <- function(freqs){
  
}
```

