---
title: "Dev Template"
author: "Taqi"
#date: "5/8/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load dependencies
library(music)
# Source files
source("../R/header.R")
.src(d = 1)
```

```{r}
buildScale("Db", "major", descending = F, play = TRUE, plot = TRUE)
Sys.sleep(4)
buildScale("Db", "major", descending = T, play = TRUE, plot = TRUE)
```

```{r}
#buildScale("Db", "lydian", descending = F, play = T, plot = F, formatNotation = T)
#buildScale("Db", "major", descending = F, play = T, plot = F, formatNotation = T)
```

```{r}
minorChord <- function(tonic){
  buildChord(tonic, chord = "minor", play = TRUE, plot = T, formatNotation = TRUE)
}
```

```{r}
buildProgression(root = "A4", play = T)
buildProgression(root = "A3", play = T, scale = "blues")
```

```{r}
while(TRUE){
  playChord(buildChord(root = "C", chord = "major9th"))
  Sys.sleep(0.5)
}
```

```{r}
chord <- noteDistance(strings("C4 Eb4 Gb4 Bb4"))
```

```{r}
A_octaves <- c(4,4,5,5,5,5,5,5)
```

```{r}
A_major <- c("A","B","C#","D","E","F#","G#","A")
A_major0 <- paste(A_major, A_octaves, sep = "")
Ab_major <- c()
for(i in seq_along(A_major)){
  Ab_major[i] <- (A_major[i] %INC% "b")
}
Ab_major <- paste(Ab_major, c(4,4,5,5,5,5,5,5), sep = "")
```

```{r}
for(i in seq_along(Ab_major)){
  playNote(A_major[i])
  Sys.sleep(0.5)
}
```
