---
title: "midi"
author: "Taqi"
date: "5/8/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# Load dependencies
library(tuneR)
library(tidyverse)
library(wesanderson)
# Source files
# This file is now just function usage template for basic-midi.R
```

```{r}
# Read midi binary data
blame_midi <- readMidi("../data-midi/blame.mid")
# Get midi dataframe
blame <- getMidiNotes(blame_midi)
# Remove velocity
blame <- blame %>% select(!contains("velocity"))
```

```{r}
# # Read midi binary data
# CDL_midi <- readMidi("../data-midi/clairedelune.mid")
# # Get midi dataframe
# CDL <- getMidiNotes(CDL_midi)
```

```{r}
.getMeter <- function(score){
  meter <- score %>% filter(event == "Time Signature")
  meter <- meter$parameterMetaSystem %>% str_split(pattern = ",")
  meter[[1]]
}
```

```{r}
# Get piece information
meter <- blame_midi %>% .getMeter
meter
```

```{r}
.getTrackNames <- function(score){ score %>% filter(event == "Sequence/Track Name") }
```

```{r}
.getTrackNames(blame_midi)
```

```{r}
.getTrack <- function(score, track_no){ score %>% filter(track == track_no) }
```

```{r}
lead_track <- blame %>% .getTrack(3)
```

```{r}
.find_rhythm <- function(rhythms, beat_ticks, bar_beats){
  (rhythms / beat_ticks) * bar_beats
}
# Evaluate the rhythms
rhythms <- lead_track$length %>% .find_rhythm(beat_ticks = 24, bar_beats = 4)
lead_track$length <- rhythms
```

```{r}
.find_measure <- function(track, bar_ticks){
  track %>% mutate(bar = 1 + as.integer(time / bar_ticks))
}
# Evaluate the measures
lead_track <- lead_track %>% .find_measure(bar_ticks = 96)
```

```{r}
levels(blame_midi$event)
```

```{r}
.getChannel <- function(score, channel){ score[which(score$channel == channel), ] }
channel7 <- blame %>% .getChannel(7)
channel8 <- blame %>% .getChannel(8)
channel9 <- blame %>% .getChannel(9)
```

