---
title: "Dev Template"
author: "Taqi"
#date: "5/8/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load dependencies
library(music)
# Source files
source("../R/header.R")
source("scales.R")
source("incidentals.R")
source("global.R")
.src(d = 1)
```

```{r}
note <- "C"; degree <- 3
# Find the number of semitones between two white keys
# In other words, the number of semitones between the scale degrees in A minor/C major
.WKsemitones <- function(note, degree){
  # Get the alphabet range for the chosen note and degree
  note_idx <- note_index(note)
  range <- .ALPH_RANGE(note_idx, degree)
  letter_range <- ALPHABET[range,]
  # Get the number of flats in range
  FLATS <- sum(letter_range[2:degree,]$HAS_FL)
  # Get the number of white keys in the range (exclude tonic)
  WHITES <- degree - 1
  # Return the number of semitones
  semitones <- FLATS + WHITES
  semitones
}
.WKsemitones(note, degree)
```

```{r}
note <- "D"; degree <- 5
.WKsemitones(note, degree)
```

```{r}
for(i in seq_along(MUS_ALPH)){
  print(.WKsemitones(MUS_ALPH[i], degree))
}
```


```{r}
tonic <- "D"
degree <- "3"
.intervalNote <- function(tonic, degree){
  # Coerce the degree as a numeric 
  degree_n <- parse_number(degree)
  # Get the number of semitones from the scale degree
  semitones <- SCALE_DEGREES[[degree]]
  # Get the target note letter (by stepping up n - 1 times)
  white <- tonic %STEP+% (degree_n - 1)
  # Find the semitones spanned
  semitones_white <- .WKsemitones(tonic, degree_n)
  # Use incidentals to find the difference
  incidental <- .incidentalSemitones(semitones - semitones_white)
  # Paste incidental the correct target note
  note <- paste(white, incidental, sep = "")
  # Return the interval
  note
}
```

```{r}
.majorScaleWK <- function(tonic){
  c(tonic, purrr::map2_chr(rep(tonic,6), DIATONIC_SCALES$major, .intervalNote))
}
```

```{r}
"C" %>% majorScale
```

```{r}
majorScale <- function(tonic){
  # Get the note letter and incidental
  note_letter <- .dropIncidental(tonic)
  incidental <- .detectIncidental(tonic)
  # Get the white key scale (i.e. using just the note letter)
  base_scale <- .majorScaleWK(note_letter)
  # If the incidental is a natural (white key), return the white key scale
  if(incidental == "natural"){ return(.majorScaleWK(tonic)) }
  # Otherwise, apply the incidental over the base scale to return the correct scale
  map_chr(base_scale, .addIncidental, incidental)
}
```

```{r}
majorScale("D#")
```

```{r}
scale <- function(tonic, scale_degrees){
  # Get the note letter and incidental
  note_letter <- .dropIncidental(tonic)
  incidental <- .detectIncidental(tonic)
  # Get the white key scale (i.e. using just the note letter)
  base_scale <- .scaleBase(note_letter, scale_degrees)
  # If the incidental is a natural (white key), return the white key scale
  if(incidental == "natural"){ return(base_scale) }
  # Otherwise, apply the incidental over the base scale to return the correct scale
  purrr::map_chr(base_scale, .addIncidental, incidental)
}
.scaleBase <- function(tonic, scale_degrees){
  c(tonic, purrr::map2_chr(rep(tonic,length(scale_degrees)), scale_degrees, .intervalNote))
}
```

```{r}
dorian <- DIATONIC_SCALES$dorian
scale("",)
```


```{r}
.WKsemitones("D", 2)
```

