---
title: "Dev Template"
author: "Taqi"
#date: "5/8/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load dependencies
library(music)
# Source files
source("../R/header.R")
.src(d = 1)
```

```{r}
MUS_ALPH <- LETTERS[1:7]
```

```{r}
MUS_ALPH
tonic <- "C"
which(MUS_ALPH == tonic)
```

```{r}
phiLetterSeq <- function(tonic, phi){
  root <- which(MUS_ALPH == tonic)
  for(i in 0:(phi-1)){
    # Wrap index to start at one
    index <- mod7(root - 1 + 4*i)
    note <- MUS_ALPH[index + 1]
    print(note)
  }
}
#phiLetterSeq("C", 7)
```

```{r}

#.IDX(2,8)
```

```{r}

```

```{r}
# C - G is a perfect fifth.
# 4 Sharps and 3 letters in between implies C - G needs no incidentalization
tonic <- "C"
# Perfect 5th scale degree
degree <- 5 
# Find number of black keys between C and G
black_keys <- BLK_KEYS_BTWN(tonic, degree = 5) 
# Disinclude C and G from boundaries
white_keys <- (degree - 2)
# Get distance between C and G
steps <- white_keys + black_keys
# Proper perfect fifth implies 7 semitones
is_P5 <- steps == 7
# If steps == 7, do nothing.
# If steps == 6, sharpen the fifth
```

```{r}
SHARPS_FIFTH <- function(i){BLK_KEYS_BTWN(MUS_ALPH[i], degree = 5)}
for(i in 1:7){ print(SHARPS_FIFTH(i)) }
```

```{r}

```

```{r}
"G#" %INC% "#"
```

```{r}
A_octaves <- c(4,4,5,5,5,5,5,5)
```

```{r}
A_major <- c("A","B","C#","D","E","F#","G#","A")
A_major0 <- paste(A_major, A_octaves, sep = "")
Ab_major <- c()
for(i in seq_along(A_major)){
  Ab_major[i] <- (A_major[i] %INC% "b")
}
Ab_major <- paste(Ab_major, c(4,4,5,5,5,5,5,5), sep = "")
```

```{r}
for(i in seq_along(Ab_major)){
  playNote(A_major[i])
  Sys.sleep(0.5)
}
```

