---
title: "Dev Template"
author: "Taqi"
#date: "5/8/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load dependencies
library(music)
# Source files
source("../R/header.R")
source("global.R")
source("scales.R")
source("incidentals.R")
.src(d = 1)
```

```{r}
note1 <- "D"
note2 <- "F#"
```

```{r}
# The smallest interval with a nonzero number of semitones in between is M2
semitones_between <- function(note1, note2, descending = FALSE){
  # Initialize offset
  offset <- 0
  # Make sure they're white keys
  if(!note1 %in% MUS_ALPH){
    root1 <- note_index(.nearestWhite(note1)[[1]])
    offset <- offset + .nearestWhite(note1)[[2]]
  } else{
    root1 <- note_index(note1)
  }
  # Get second note
  if(!note2 %in% MUS_ALPH){
    root2 <- note_index(.nearestWhite(note2)[[1]])
    offset <- offset + .nearestWhite(note2)[[2]]
  } else{
    root2 <- note_index(note2) - 1
  }
  if(!descending){ if(root2 < root1){ root2 <- root2 + 7 }}
  range <- .IDXR((root1+1):(root2-1))
  
  #if(length(range) == 3){range <- range[2]}
  #else if(length(range) > 3){range }
  length(range) + sum(ALPHABET[range,"HAS_SH"]) + sum(ALPHABET[range,"HAS_FL"]) + offset
}
semitones_between("D","G") + 2
```

```{r}
INTERVAL_MATRIX <- function(){
  intervals <- matrix(rep(0, 49), nrow = 7)
  for(i in seq_along(MUS_ALPH)){
    for(j in seq_along(MUS_ALPH)){
      intervals[i,j] <- semitones_between(MUS_ALPH[i], MUS_ALPH[j])
    }
  }
  intervals
}
intervals <- INTERVAL_MATRIX()
colnames(intervals) <- MUS_ALPH
rownames(intervals) <- MUS_ALPH
```

```{r}
# Enharmonics
.nearestWhite("Gx") == "A"
.nearestWhite("B#") == "C"
#.nearestWhite("Fb") == ("E",0) or ("F", 1)?

# Simple incidentals
.nearestWhite("Ab")
```


```{r}
SCALE_DEGREES$b7
```

