---
title: "Dev Template"
author: "Taqi"
#date: "5/8/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load dependencies
library(music)
# Source files
source("../R/header.R")
source("scales.R")
source("incidentals.R")
source("global.R")
.src(d = 1)
```

```{r}
note <- "C"; degree <- 3
# Find the number of semitones between two white keys
# In other words, the number of semitones between the scale degrees in A minor/C major
.WKsemitones <- function(note, degree){
  # Get the note index
  note_idx <- note_index(note)
  range <- .ALPH_RANGE(note_idx, degree)
  # Get the number of flats in range
  FLATS <- sum(ALPHABET[range,]$HAS_FL)
  # Get the number of white keys in the range
  WHITES <- degree - 2
  # Return the number of semitones
  semitones <- FLATS + WHITES
  semitones
}
.WKsemitones(note, degree)
```

```{r}
tonic <- "D"
degree <- "3"
.intervalNote <- function(tonic, degree){
  # Coerce the degree as a numeric 
  degree_n <- parse_number(degree)
  # Get the number of semitones from the scale degree
  semitones <- SCALE_DEGREES[[degree]]
  # Get the target note letter (by stepping up n - 1 times)
  white <- tonic %STEP+% (degree_n - 1)
  # Find the semitones spanned
  semitones_white <- .WKsemitones(tonic, degree_n)
  # Use incidentals to find the difference
  incidental <- .incidentalSemitones(semitones - semitones_white)
  # Paste incidental the correct target note
  note <- paste(white, incidental, sep = "")
  # Return the interval
  note
}
```

```{r}
tonic <- "D"
#.intervalNote(tonic, "3")
D_major <- c(tonic, map2_chr(rep(tonic,6), DIATONIC_SCALES$major, .intervalNote))
D_major
```


```{r}
.WKsemitones("D", 2)
```

