---
title: "Development Template"
author: "Taqi"
# date: "4/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load libraries
library(tidyverse)
# Source files
source("../R/header.R")
.src(1)
```

```{r}
# Bach score file path
bach_spline <- "../scores/bach_C_notes.krn"
bach <- piece_df(v = bach_spline, instruments = c("Piano"))
```

```{r}
piece_df <- function(v, instruments){
  len <- length(v)
  c <- vector()
  master_colnames <- c("key","meter","measure","rhythm","name","value")
  first <- T
  for(i in 1:len){
    Ai <- kern2df(v[i])
    if(first){piece <- Ai} else{piece <- cbind(piece,Ai[,-(1:3)])}
    max_notes <- (ncol(Ai)-3)/3
    for(k in 1:max_notes){
      if(first){col_names <- master_colnames} else{col_names <- master_colnames[3:6]}
      c_i <- vector()
      for(j in 1:length(cols)){
        c_i[j] <- paste(instruments[i],"_",cols[j],k,sep = "",collapse="")
      }
      c <- c(c,c_i)
      first <- F
    }
  }
  colnames(piece) <- c
  piece
}
```

# Old implementation

```{r}
piece_df <- function(v, instruments){
  len <- length(v)
  c <- vector()
  first <- T
  for(i in 1:len){
    Ai <- kern2df(v[i])
    if(first){
      piece <- Ai
    }
    if(!first){
      piece <- cbind(piece,Ai[,-(1:3)])
    }
    max_notes <- (ncol(Ai)-3)/4
    for(k in 1:max_notes){
      if(first){cols <- c("key","meter","measure","r.v","n.o","n.n","n.v")}
      if(!first){cols <- c("r.v","n.o","n.n","n.v")}
      c_i <- vector()
      for(j in 1:length(cols)){
        c_i[j] <- paste(instruments[i],"_",cols[j],k,sep = "",collapse="")
      }
      c <- c(c,c_i)
      first <- F
    }
  }
  colnames(piece) <- c
  piece
}
```

